name: Run HSIC

# Triggers the workflow on push events to the main branch
on:
  push:
    branches:
      - tn_2  # Triggers when you push to the main branch

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: |
          python experiment_top_left_test.py --lambd 0.1 --lambd_test 0.1 
          python experiment_top_left_test.py --lambd 0.1 --lambd_test 0.5 
          python experiment_top_left_test.py --lambd 0.1 --lambd_test 0.9 
          python experiment_top_left_test.py --lambd 0.5 --lambd_test 0.1 
          python experiment_top_left_test.py --lambd 0.5 --lambd_test 0.5 
          python experiment_top_left_test.py --lambd 0.5 --lambd_test 0.9  
          python experiment_top_left_test.py --lambd 0.9 --lambd_test 0.1 
          python experiment_top_left_test.py --lambd 0.9 --lambd_test 0.5 
          python experiment_top_left_test.py --lambd 0.9 --lambd_test 0.9 
      
      - name: Commit and push file
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
          